version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "com.sonyericsson.jenkins.plugins.bfa:build-failure-analyzer"
        # Buggy release
        versions: ["2.27.0"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
